In [47]:
import math
def targetfunc(x):
    return math.sin(x / 5) * math.exp(x / 10) + 5 * math.exp(-x / 2)


print targetfunc(1.0)

3.25221686527


In [48]:
b = [targetfunc(1.), targetfunc(4.),targetfunc(10.), targetfunc(15.)]
print b

[3.252216865271419, 1.7468459495903677, 2.5054164070002463, 0.6352214195786656]


In [49]:
import numpy
A = numpy.zeros((4,4))
A[0,:] = [1.,1.,1.,1.]
A[1,:] = [1.,4.,16.,64.]
A[2,:] = [1.,10.,100.,1000.]
A[3,:] = [1.,15.,15.**2,15.**3]
print A

[[1.000e+00 1.000e+00 1.000e+00 1.000e+00]
 [1.000e+00 4.000e+00 1.600e+01 6.400e+01]
 [1.000e+00 1.000e+01 1.000e+02 1.000e+03]
 [1.000e+00 1.500e+01 2.250e+02 3.375e+03]]


In [50]:
#import numpy as np
from scipy import linalg
x = linalg.solve(A,b)
print x

[ 4.36264154 -1.29552587  0.19333685 -0.00823565]


In [51]:
print A.dot(x)

[3.25221687 1.74684595 2.50541641 0.63522142]


In [52]:
print x[0] + x[1] + x[2] + x[3] - b[0]

0.0


In [43]:
print x[0] + x[1] * 15 + x[2] * (15**2) + x[3]*(15**3) - b[3]

print targetfunc(2)

-7.216449660063518e-16
1.83939720586


In [42]:
import numpy as np
import matplotlib.pyplot as plt

rr = np.arange(1, 15.1, 0.05)
yy = map(targetfunc,rr)
plt.plot([1, 2, 3, 4], [1, 4, 9, 16])
#plt.plot(rr,yy)
plt.show()

AttributeError: 'module' object has no attribute 'to_rgba'